config/routes.rb
Betastore::Application.routes.draw do
  resources :subscriptions
  get '/products' => 'products#index'


  resources :products do
    member do
      post 'vote_up'
      post 'vote_down'
    end
  end

  namespace :admin do
    resources :products

    get  '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'


    # get '/products' => 'products#index', as: 'index'
    # get '/products/new' => 'products#new', as: 'new_product'
    # post'/products' => 'products#create'
    # get '/products/:id' => 'products#show', as: 'product'

#    get '/products'          => 'products#index', as: 'products'
#   post '/products'          => 'products#create'
#    get '/products/new'      => 'products#new',   as: 'new_product'
#    get '/products/:id/edit' => 'products#edit',  as: 'edit_product'
#    get '/products/:id'      => 'products#show',  as: 'product'
#  patch '/products/:id'      => 'products#update'
# delete '/products/:id'      => 'products#destroy

  end

  root :to => 'subscriptions#new'


end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :line_items, :through => :orders
  has_many :products, :through => :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  after_save :calculate_order_total_amount
  after_destroy :calculate_order_total_amount

  def calculate_order_total_amount
    order.calculate_total_amount
  end

  def total_amount
    product.price * quantity
  end



end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :line_items
  has_many :products, :through => :line_items


  def self.recent
    where("placed_at > ?", 7.days.ago)
  end

  def self.by(customer)
    where(customer_id: customer.id)
  end

  def calculate_total_amount
    self.total_amount = 0
    for line_item in line_items
      self.total_amount += line_item.total_amount
    end
    save
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items

  validates :name, presence: {message: "is required"}
  validates :price, numericality: { greater_than_or_equal_to: 0, message: "isn't a number" }
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false
end

app/controllers/admin/logins_controller.rb
class Admin::LoginsController < ApplicationController
  layout 'admin'

  skip_before_action :require_login

  def create
    user = User.find_by(email: params[:email])
    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to admin_products_path
    else
      flash.now[:danger] = 'Log In Failed'
      render 'new'
    end
  end

end

app/controllers/admin/products_controller.rb
  class Admin::ProductsController < ApplicationController

  def index
    if logged_in?
      @products = Product.order('name')
    else
      redirect_to admin_login_path, alert: 'Please log in to continue'
    end
  end

  def show
    @id = params[:id]
    @product = Product.find(@id)
  end

  def new
    @product = Product.new
  end

  def create
  @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Product #{@product.name} was created."
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end


  def update
    @id = params[:id]
    @product = Product.find(@id)
      if @product.update(product_params)
        redirect_to admin_products_path, notice: "Product #{@product.name} was updated."
      else
        render 'edit'
      end
  end

  def destroy
    @id = params[:id]
    @product = Product.find(@id)
    if @product.destroy
      redirect_to admin_products_path, notice: "Product #{@product.name} was deleted."
    else
      render 'show'
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :price)
    end
  end


  #TODO
  # implement the actions
  # create routes for those actions
  # create a button_to in order to exercise the routes

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login


  def logged_in?
    session[:user_id].present?
  end

  def require_login
    unless logged_in?
      redirect_to admin_login_path, danger: 'Please log in to continue'
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('name')
  end


  def vote_up
    product = Product.find(params[:id])
    product.increment(:votes)
    product.save
    redirect_to products_path
  end

  def vote_down
    product = Product.find(params[:id])
    product.decrement(:votes)
    product.save
    redirect_to products_path
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      redirect_to new_subscription_path,
        notice: 'Subscription was successfully created.'
    else
      render action: 'new'
    end
  end

  private
  def subscription_params
    params.require(:subscription).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/login/new.html.erb
<div class="jumbotron">
  <%= form_tag admin_logins_path, class: 'form-horizontal', role: 'form' do %>

    <div class="form-group">
      <%= label_tag :email, nil, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= email_field_tag :email, params[:email], class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :password, nil, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= password_field_tag :password, nil, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-4">
        <%= submit_tag "Log In", class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/logins/new.html.erb
<div class="jumbotron">
  <%= form_tag admin_logins_path, class: 'form-horizontal', role: 'form' do %>

    <div class="form-group">
      <%= label_tag :email, nil, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= email_field_tag :email, params[:email], class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :password, nil, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= password_field_tag :password, nil, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-4">
        <%= submit_tag "Log In", class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.submit %>
<% end %><br>

<% for error in @product.errors.full_messages %>
  <div class="error"><%= error %></div>
<% end %><br>

<a href="<%= admin_products_path %>">Go back to Index</a>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<% if flash[:notice].present? %>
  <div class="notice"><%= flash[:notice] %></div><br>
<% end %>

<div>
  <%= link_to '', new_admin_product_path, class:'glyphicon glyphicon-plus'%>
  New Product
</div>




<table class="table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created At</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= product.id %></td>
      <td><%= link_to product.name, admin_product_path(product), class: "show-tooltip", title: "Link to #{product.name}" %></td>
      <td><%= number_to_currency product.price %></td>
      <td><%= product.created_at %></td>
      <div class='btn-group'>
        <td><%= link_to("Edit", edit_admin_product_path(product), {method:"get", class:"btn btn-default"}) %></td>
        <td><%= link_to("Delete", admin_product_path(@products), {method: "delete", data: { confirm: "Are you sure?" }, class:"btn btn-default"}) %></td>
        <td><%= button_to("Vote Up", vote_up_product_path(product), {method:"post", class:"btn btn-default"}) %></td>
        <td><%= button_to("Vote Down", vote_down_product_path(product), {method:"post", class:"btn btn-default"}) %></td>
      </div>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<%= form_for [:admin, @product], {html: {roll: 'form'}} do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :price %>
    <%= f.text_field :price, class:'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class:'form-control' %>
  </div>

    <%= f.submit %>
<% end %><br>

<% for error in @product.errors.full_messages %>
  <div class="error"><%= error %></div>
<% end %><br>


<a href="<%= admin_products_path %>">Go Back to Index</a>


<!-- <% if @product.errors.full_messages.present? %>
  <div class="notice"><%= @product.errors.full_messages %></div>
<% end %> -->

app/views/admin/products/show.html.erb
<h1>Products</h1>

<!-- <% if flash[:notice].present? %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %> -->

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created At</th>
  </tr>

  <tr>
    <td><%= @product.id %></td>
    <td><%= @product.name %></td>
    <td><%= @product.price %></td>
    <td><%= @product.created_at %></td>
    <td><%= image_tag @product.image_url, alt: @product.image_url %></td>
  </tr>
</table>

<a href="<%= edit_admin_product_path %>">Edit Product</a><br><br>
<a href="<%= admin_products_path %>">Go back to Index</a><br>
<br>
<br>
<%= button_to("Delete", admin_product_path(@product), {method: "delete", data: { confirm: "Are you sure?" }}) %>


<a href="http://calebjacob.com" class="roll-over-item">Link</a>
<span class="more-info"> See More Stuff </span>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Betamore</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/index.html.erb
<h1>This is a list of products</h1>
<ul>
  <% for product in @products %>
    <li><%= product.name %></li>
  <% end %>
</ul>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <div class="field">
    <%= f.label :email, "Let me know when we go live:" %>
    <%= f.text_field :email %>
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

<% if flash.present? %>
  <% flash.each do |k,v| %>
    <div class="<%= k %>"><%= v %></div>
  <% end %>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<%= render 'form' %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>